# coding: utf-8

"""
    Simple calc API

    This a simple API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_addition_get(self):
        """Test case for addition_get

        """
        pass

    def test_division_get(self):
        """Test case for division_get

        """
        pass

    def test_multiplication_get(self):
        """Test case for multiplication_get

        """
        pass

    def test_substraction_get(self):
        """Test case for substraction_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
